--
-- 
-- 
-- COVERING INDEX: É UM ÍNDICE QUE CONTÉM TODAS AS COLUNAS NECESSÁRIAS PARA A CONSULTA, EVITANDO A NECESSIDADE DE ACESSAR A TABELA PRINCIPAL. POR ISSO A BOA PRÁTICA É SELECIONAR APENAS AS COLUNAS NECESSÁRIAS.
-- 
-- 
SELECT "id", "email" FROM "users" WHERE "email" = 'lara.pereira6863@example.com';
EXPLAIN QUERY PLAN SELECT "id", "email" FROM "users" WHERE "email" = 'lara.pereira6863@example.com';
EXPLAIN QUERY PLAN SELECT * FROM "users" WHERE "email" = 'lara.pereira6863@example.com';
-- 
-- 
-- COMPOSTOS: ÍNDICES COMPOSTOS SÃO AQUELES QUE ENVOLVEM MAIS DE UMA COLUNA. ELES SÃO ÚTEIS QUANDO AS CONSULTAS FREQUENTEMENTE FILTRAM OU ORDENAM POR MÚLTIPLAS COLUNAS. QUANDO DEFINIMOS UMA PRIMARY KEY OU UNIQUE COMPOSTOS, UM ÍNDICE COMPOSTO É CRIADO AUTOMATICAMENTE. A ORDEM DAS COLUNAS NA CRIAÇÃO É IMPORTANTE. A COLUNA MAIS SELETIVA (COM MAIOR CARDINALIDADE) DEVE SER A PRIMEIRA.
-- 
-- SE DEFINIMOS UMA PRIMARY KEY COMPOST, UM ÍNDICE COMPOSTO É CRIADO AUTOMATICAMENTE.
-- A ORDEM QUE DEFINIMOS AQUI ("user_id", "course_id", "lesson_id") IMPORTA!
CREATE INDEX "idx_lc_user_lesson" ON "lessons_completed" ("user_id", "course_id", "lesson_id");

-- USA O ÍNDICE COMPOSTO
EXPLAIN QUERY PLAN SELECT "user_id", "course_id", "lesson_id"
FROM "lessons_completed"
WHERE "course_id" = 1 AND "user_id" = 1;

-- NÃO USA O ÍNDICE COMPOSTO, POIS A COLUNA USER_ID NÃO É A PRIMEIRA
EXPLAIN QUERY PLAN SELECT * FROM "lessons_completed" WHERE "course_id" = 1;
EXPLAIN QUERY PLAN SELECT * FROM "lessons_completed" WHERE "lesson_id" = 1;
-- 
-- 
-- 
-- PARCIAL: ÍNDICES PARCIAIS SÃO AQUELES QUE INDEXAM APENAS UMA PARTE DOS DADOS DE UMA TABELA, COM BASE EM UMA CONDIÇÃO ESPECÍFICA. ELES SÃO ÚTEIS PARA MELHORAR A PERFORMANCE DE CONSULTAS QUE FILTRAM POR ESSA CONDIÇÃO.
-- 
CREATE INDEX "idx_users_vitalicio" ON "users" ("name") WHERE "vitalicio" = 1;
-- USA O ÍNDICE PARCIAL
SELECT * FROM "users" WHERE "name" = 'Ana Júlia Carvalho' AND "vitalicio" = 1;
-- NÃO USA O ÍNDICE PARCIAL, POIS A CONDIÇÃO VITALICIO NÃO É ATENDIDA
SELECT * FROM "users" WHERE "name" = 'Ana Júlia Carvalho' AND "vitalicio" = 0;
EXPLAIN QUERY PLAN SELECT * FROM "users" WHERE "name" = 'Ana Júlia Carvalho' AND "vitalicio" = 1;
