--
-- 
-- 
-- CREATE INDEX: CRIA UM ÍNDICE E O 'DROP INDEX' REMOVE O ÍNDICE
-- CREATE INDEX "nome_indice" ON "nome_tabela" ("coluna", ...)
CREATE INDEX "idx_users_created" ON "users" ("created");
DROP INDEX "idx_users_created";

SELECT * FROM "users" WHERE "created" = '2020-05-03 17:47:09';
EXPLAIN QUERY PLAN SELECT * FROM "users" WHERE "created" = '2020-05-03 17:47:09';
-- 
-- 
-- 
-- CUSTO: OS ÍNDICES OCUPAM ESPAÇO EM DISCO E MEMÓRIA, E PODEM IMPACTAR A PERFORMANCE DO INSERT, UPDATE E DELETE, POIS O ÍNDICE TAMBÉM PRECISA SER ATUALIZADO.
-- 
-- 
-- 1_000_000 DE PRODUTOS, EM UMA TABELA COM 5.750 GB
-- AO CRIAR UM ÍNDICE, O TAMANHO DO DB AUMENTOU PARA 5.770 GB
-- O ÍNDICE OCUPOU CERCA DE 20 MB
SELECT COUNT(*) FROM "products";
SELECT * FROM "products" WHERE "sku" = 'U4XMSABD3HN1';
CREATE INDEX "idx_products_sku" ON "products" ("sku");
-- 
-- 
-- 
-- QUANDO CRIAR?
-- 
-- SELECT, INSERT, UPDATE e DELETE
-- A NECESSIDADE DOS ÍNDICES VEM DAS COLUNAS FREQUENTEMENTE USADAS EM 'WHERE', 'GROUP BY', 'JOIN ON' OU 'ORDER BY'.
-- 
-- CARDINALIDADE: OUTRA VARIÁVEL É A CARDINALIDADE DA COLUNA, OU SEJA, A QUANTIDADE DE VALORES ÚNICOS, QUANTO MAIOR A CARDINALIDADE, MAIS ÚTIL SERÁ O ÍNDICE.
-- 
SELECT COUNT(DISTINCT "sku") AS "card" FROM "products";
SELECT COUNT(DISTINCT "vitalicio") AS "card" FROM "users";
-- 
-- 0 - 100, QUANTO MAIS PRÓXIMO DE 100, MAIS ÚTIL SERÁ O ÍNDICE
SELECT (100 * COUNT(DISTINCT "sku") / COUNT(*)) AS "card" FROM "products";
SELECT (100 * COUNT(DISTINCT "free") / COUNT(*)) AS "card" FROM "lessons";
